In [1]:
import os
import sys
import time
sys.path.insert(0,'..')

from classificationConfig import CONFIG
import numpy as np
import pandas as pd
from sklearn.utils import class_weight

import multiprocessing

from NeuralNetworkAnalysis import NeuralNetworkAnalysis as nna

from Functions.MetricCustom import ind_SP

num_processes = multiprocessing.cpu_count()

analysis_name = 'Classification'

data_path = CONFIG['OUTPUTDATAPATH']
results_path = CONFIG['PACKAGE_NAME']
class_interest = [1,2,3,4]#[6,7,9,16,21,23]

nums_componets = None

Using TensorFlow backend.


In [1]:
#Function for Dataset
from Functions.dataset.shipClasses import LoadData
import numpy as np

dt_24 = LoadData()
dt_24.infoData()
all_data,all_trgt= dt_24.getData()

Using TensorFlow backend.


[+] Time to read data file: 2.90071892738 seconds
analysis of Class01: 
size: 3209x400 -- maxValue: 1.38463282277 -- minValue: -0.199999448771
analysis of Class02: 
size: 3037x400 -- maxValue: 1.34259549045 -- minValue: -0.199998892824
analysis of Class03: 
size: 3212x400 -- maxValue: 1.49508318988 -- minValue: -0.199998792195
analysis of Class04: 
size: 3203x400 -- maxValue: 1.38544304863 -- minValue: -0.199999766141
analysis of Class05: 
size: 4781x400 -- maxValue: 2.08462558961 -- minValue: -0.199999495607
analysis of Class06: 
size: 2232x400 -- maxValue: 1.03378591259 -- minValue: -0.199999021577
analysis of Class07: 
size: 10821x400 -- maxValue: 1.70564969417 -- minValue: -0.199999701918
analysis of Class08: 
size: 5898x400 -- maxValue: 2.29338655988 -- minValue: -0.199999534352
analysis of Class09: 
size: 14562x400 -- maxValue: 2.27570297485 -- minValue: -0.199999369207
analysis of Class10: 
size: 23224x400 -- maxValue: 2.98432190517 -- minValue: -0.19999981523
analysis of Class1

In [2]:
class_interest = [1,2,9,10,13,14,16,21,22,23]

dt_24.setRangeClass(map(lambda x:x-1,class_interest))
#map(lambda x:x-1,class_interest)

In [3]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
print dt_24.class_labels
le.fit(dt_24.class_labels)
print le.classes_
y_label = le.inverse_transform(map(int,dt_24.all_trgt))

['Class01', 'Class02', 'Class09', 'Class10', 'Class13', 'Class14', 'Class16', 'Class21', 'Class22', 'Class23']
['Class01' 'Class02' 'Class09' 'Class10' 'Class13' 'Class14' 'Class16'
 'Class21' 'Class22' 'Class23']


/home/venancio/sonarteste/lib/python2.7/site-packages/sklearn/preprocessing/label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:


In [4]:
map_classes = {'ClassA1':['Class{0:02d}'.format(i) for i in [9,10,13,14,16]],
               'ClassA2':['Class{0:02d}'.format(i) for i in [1,2,22,23]],
               'ClassA3':'Class21'}


dt_24.mapClasses(map_classes)

/home/venancio/sonarteste/lib/python2.7/site-packages/sklearn/preprocessing/label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:


In [5]:
dt_24.class_labels

['ClassA1', 'ClassA2', 'ClassA3']

In [4]:
dt_24.infoData()

analysis of ClassA1: 
size: 73875x400 -- maxValue: 4.19032063272 -- minValue: -0.199999971812
analysis of ClassA2: 
size: 68060x400 -- maxValue: 2.77933588329 -- minValue: -0.1999999395
analysis of ClassA3: 
size: 5292x400 -- maxValue: 2.00508879586 -- minValue: -0.199999952879
end of class analysis


In [14]:
teste = [len(dt_24.all_trgt[dt_24.all_trgt==i]) for i in range(3)]
for i in teste:
    print i

73875
68060
5292


In [5]:
from Functions.preprocessing import CVClassifier

cvo = CVClassifier(,dt_24.all_data,dt_24.all_trgt,n_folds=10)


10

In [2]:
#DataModule

analysis = nna(analysis_name="NeuralNetwork",development_flag=True,development_events=400,verbose=False)
#analysis.infoData()
#analysis.setRangeClass([i-1 for i in class_interest])
#analysis.balanceData()
#analysis.infoData()
weight_class = analysis.getClassesWeight(flag=True)
all_data,all_trgt,_ = analysis.getData()

[+] Time to read data file: 2.91407179832 seconds


In [4]:
#from sklearn.neural_network import MLPClassifier
#from hep_ml.nnet import MLPClassifier
#from hep_ml.nnet import MLPMultiClassifier
from Functions.MLPClassification import MLPSKlearn

from sklearn.preprocessing import StandardScaler,OneHotEncoder
from sklearn.model_selection import train_test_split
from sklearn.ensemble import AdaBoostClassifier,VotingClassifier

#mlp = MLPClassifier(hidden_layer_sizes=(40,),
#                    activation='tanh',
#                    solver='adam',
#                    alpha=0.0001, 
#                    batch_size='auto',
#                    learning_rate='constant',
#                    learning_rate_init=0.001,
#                    power_t=0.5,
#                    max_iter=1000,
#                    shuffle=True,
#                    random_state=None,
#                    tol=0.01,
#                    verbose=True,
#                    warm_start=False,
#                    momentum=0.9,
#                    nesterovs_momentum=True,
#                    early_stopping=True,
#                    validation_fraction=0.2,
#                    beta_1=0.9,
#                    beta_2=0.999,
#                    epsilon=1e-08)

#neural = MLPClassifier(layers=[10], trainer='adadelta', trainer_parameters={'batch': 600})
#mlp = MLPMultiClassifier(layers=(10,), scaler='standard', trainer='irprop-', epochs=100,
#                 trainer_parameters=None, random_state=None)

mlp = MLPSKlearn()


estimator = 5
classifier = AdaBoostClassifier(base_estimator=mlp, n_estimators=estimator)
#mlp = MLPClassifier()
#mj_vot = VotingClassifier(tuple(classifier.estimators_),n_jobs=-1)
#preprocessing
X_train, X_test, y_train, y_test = train_test_split(all_data, all_trgt, test_size=0.2)

print 'shape of X_train: %d'%X_train.shape[0]
print 'shape of X_test: %d'%X_test.shape[0]
print 'shape of y_train: %d'%y_train.shape[0]
print 'shape of y_test: %d'%y_test.shape[0]

scale = StandardScaler().fit(X_train)
data_preproc_train = scale.transform(X_train)
data_preproc_test = scale.transform(X_test)
ohe = OneHotEncoder(sparse=False)
trgt_preproc =ohe.fit_transform(pd.DataFrame(y_train,columns=['target']))

shape of X_train: 176130
shape of X_test: 44033
shape of y_train: 176130
shape of y_test: 44033


In [5]:
#Usingo only MLP simple 
#mlp.fit(data_preproc_train,y_train)

#using MLP with boosting

classifier.fit(X_train,y_train)

#mj_vot = VotingClassifier(zip(['est{0}'.format(i) for i in range(estimator)],
#                              classifier.estimators_),
#                          n_jobs=-1)
#using votMaj with boosting MLP
#mj_vot.fit(X_train,y_train)

[+] 1 of 1 inits
Epoch 1/20
176130/176130 [==============================] - 3s 17us/step - loss: 2.2882e-07 - acc: 0.0809
Epoch 2/20
176130/176130 [==============================] - 3s 16us/step - loss: 2.0793e-07 - acc: 0.2370
Epoch 3/20
176130/176130 [==============================] - 3s 16us/step - loss: 1.8676e-07 - acc: 0.3528
Epoch 4/20
176130/176130 [==============================] - 3s 16us/step - loss: 1.7380e-07 - acc: 0.4075
Epoch 5/20
176130/176130 [==============================] - 3s 16us/step - loss: 1.6518e-07 - acc: 0.4424
Epoch 6/20
176130/176130 [==============================] - 3s 16us/step - loss: 1.5845e-07 - acc: 0.4718
Epoch 7/20
176130/176130 [==============================] - 3s 16us/step - loss: 1.5264e-07 - acc: 0.4988
Epoch 8/20
176130/176130 [==============================] - 3s 16us/step - loss: 1.4774e-07 - acc: 0.5188
Epoch 9/20
176130/176130 [==============================] - 3s 16us/step - loss: 1.4359e-07 - acc: 0.5356
Epoch 10/20
176130/176130 [==

AdaBoostClassifier(algorithm='SAMME.R',
          base_estimator=MLPSKlearn(activation=None, alpha=None, batch_size=None, beta_1=None,
      beta_2=None, dir=None, early_stopping=None, epsilon=None,
      hidden_layer_sizes=None, learning_rate=None, learning_rate_init=None,
      max_iter=None, momentum=None, n_iter_no_change=None,
      nesterovs_momentum=None, power_t=None, shuffle=None, solver=None,
      tol=None, validation_fraction=None, verbose=None, warm_start=None),
          learning_rate=1.0, n_estimators=5, random_state=None)

In [ ]:
for est in classifier.estimators_:
    print est.predict(X_test)

In [9]:
from sklearn.metrics import classification_report


output_classes = mj_vot.predict(X=X_test)
print classification_report(y_pred=output_classes,y_true=y_test)

             precision    recall  f1-score   support

          0       1.00      1.00      1.00         9
          1       1.00      0.67      0.80         9
          2       0.80      1.00      0.89        12

avg / total       0.92      0.90      0.90        30



/home/venancio/sonarteste/lib/python2.7/site-packages/sklearn/preprocessing/label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:


In [27]:
for each_mlp in classifier.staged_predict_proba(X_test):
    print each_mlp

[[2.22044605e-16 3.21770927e-02 9.67822907e-01]
 [2.22044605e-16 9.99843719e-01 1.56280545e-04]
 [2.22044605e-16 9.99964050e-01 3.59500227e-05]
 [2.22044605e-16 3.71907841e-05 9.99962809e-01]
 [2.22044605e-16 1.06661147e-03 9.98933389e-01]
 [1.00000000e+00 2.22044605e-16 2.22044605e-16]
 [2.22044605e-16 2.71301116e-04 9.99728699e-01]
 [2.22044605e-16 4.02871556e-05 9.99959713e-01]
 [1.00000000e+00 2.22044605e-16 2.22044605e-16]
 [2.22044605e-16 1.94059398e-01 8.05940602e-01]
 [2.22044605e-16 9.99922729e-01 7.72705063e-05]
 [2.22044605e-16 1.40534761e-05 9.99985947e-01]
 [2.22044605e-16 2.20618720e-02 9.77938128e-01]
 [2.22044605e-16 9.99236248e-01 7.63752128e-04]
 [1.00000000e+00 2.22044605e-16 2.22044605e-16]
 [1.00000000e+00 2.22044605e-16 2.22044605e-16]
 [2.22044605e-16 9.99221564e-01 7.78435675e-04]
 [1.00000000e+00 2.22044605e-16 2.22044605e-16]
 [1.00000000e+00 2.22044605e-16 2.22044605e-16]
 [2.22044605e-16 2.78683062e-04 9.99721317e-01]
 [2.22044605e-16 1.35665469e-06 9.999986

In [99]:
import inspect
from sklearn.utils.testing import all_estimators
for name, clf in all_estimators(type_filter='classifier'):
    if 'sample_weight' in inspect.getargspec(clf().fit)[0]:
        print name

AdaBoostClassifier
BaggingClassifier
BernoulliNB
CalibratedClassifierCV
DecisionTreeClassifier
ExtraTreeClassifier
ExtraTreesClassifier
GaussianNB
GradientBoostingClassifier
LinearSVC
LogisticRegression
LogisticRegressionCV
MultinomialNB
NuSVC
Perceptron
RandomForestClassifier
RidgeClassifier
RidgeClassifierCV
SGDClassifier
SVC


In [100]:
def _validate_sample_weight(self, sample_weight, n_samples):
        """Set the sample weight array."""
        if sample_weight is None:
            # uniform sample weights
            sample_weight = np.ones(n_samples, dtype=np.float64, order='C')
        else:
            # user-provided array
            sample_weight = np.asarray(sample_weight, dtype=np.float64,
                                       order="C")
        if sample_weight.shape[0] != n_samples:
            raise ValueError("Shapes of X and sample_weight do not match.")
        return sample_weight

In [101]:
n_samples, n_features = X.shape

In [102]:
print n_samples,n_features

150 4
